language: php

php:
  - "5.4"
  - "5.5"
  - "5.6"

before_script:
  - travis_retry composer self-update
  - travis_retry composer install

script: vendor/bin/phpunit --verbose

branches:
  only:
    - "master"
